### ISSUE TITLE
Support for multi-platform docker containers

### ISSUE THREAD

**Issue by sjunges** [moves-rwth/docker-storm#8]
See https://docs.docker.com/build/building/multi-platform/, which avoids QEMU

**Comment by volkm** [comment]
My proposal is to use [multiple runners in Github actions](https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners) to build the different platform images. The build would most likely be slow for the emulated runners, but at least we get multi-platform images. If arm64 runners are available in the CI at some point (probably [end of the year](https://github.blog/changelog/2024-06-03-actions-arm-based-linux-and-windows-runners-are-now-in-public-beta/)), we could easily switch to a native build.

Another possibility in the meantime could be to build the amd64 images via the CI and manually build arm64 on our Macbook. Then we could manually merge [both image types into one](https://www.docker.com/blog/multi-platform-docker-builds/#manifest-lists).
